### ISSUE TITLE
ASlink-Warning-Size limit exceeded in bank ram

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#23]
As said in title, I got this warning when compiling my project: "ASlink-Warning-Size limit exceeded in bank ram"

What does that mean exactly?
What can I do to fix that?

Regards,
Alexandre

**Comment by malbanGit** [comment]
Well...

The Vectrex is a "little" machine. For C it has only 896 bytes of RAM.
If you used that all up - you are in trouble.
Often "static" can be held in ROM instead of RAM - feel free to use the
"C" word "const" often :-)

Am 19.05.2020 09:53 schrieb AlexandreMinard: 

> As said in title, I got this warning when compiling my project: "ASlink-Warning-Size limit exceeded in bank ram" 
> 
> What does that mean exactly?
> What can I do to fix that? 
> 
> Regards,
> Alexandre 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/23
[2]

**Comment by AlexandreMinard** [comment]
OK Thanks
