### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#24]
Even if I set conditional directives like

```
#ifndef FILE_H
#define FILE_H

const signed char cross[]={
.....
};

#endif
```

I got the warning message "multiple definitions of cross" when compiling.

**Comment by malbanGit** [comment]
...
just because the "#defines" are in there, doesn't mean that it might not
be compiled twice in different objects.
Usually in "h" (header) files you only put definitions used by other
files, NOT the actual data.

The "h" files should define the definitions (and can be included by
other files)...
And the accompanying "c" file (or asm...) should hold the actual object
- or data...

Am 19.05.2020 11:09 schrieb AlexandreMinard: 

> Even if I set conditional directives like 
> 
> #ifndef FILE_H
> #define FILE_H
> 
> const signed char cross[]={
> .....
> };
> 
> #endif
> 
> I got the warning message "multiple definitions of cross" when compiling. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/24
[2]

**Comment by AlexandreMinard** [comment]
OK got it, thanks
