### ISSUE TITLE
Popping sound while debugging

### ISSUE THREAD

**Issue by mountaingoate** [malbanGit/Vide#3]
While the software is being paused either from vexci or stopped at a breakpoint in dissi, random popping sound can come from the computer speakers.

Seems like a single pop for each execution stop.

**Comment by malbanGit** [comment]
This is new to me, doesn't happen at my place otherwise I would have noticed.
For clarification, does this sound happen while pausing without your interfering in any way?

Or if you "pause" and than do a "step" of some sort? And than with each step?

Anyway both would be quite "interesting" since sound should be completely turned off (at least sound emulation) while in single step mode...

**Comment by mountaingoate** [comment]
Here is how the popping manifests itself on my system.
During normal running in the emulator, there is no popping.
When the emulator is paused, there is one small pop.
When the run button is pressed, there is one small pop.

When stopping the software with a breakpoint, there are two small pops in quick succession. Stepping forward from the breakpoint does does not give the popping sound, only stopping at them.

**Comment by mountaingoate** [comment]
I noticed that the emulator runs slower on my machine than "real time". When playing a music it is also slower so much so that it has a deeper tone.

Can this be related to the popping?

**Comment by malbanGit** [comment]
Well, if you don't have a fast computer, emulation might be slow - since its pure java and emulation with everything switched on is quite detailed. But still I don't think that should be it. I have some other issues I am looking into right now, after that I will startup a window machine and do some testing...

**Comment by malbanGit** [comment]
Hello,
I have run VIDE on my parallels emulated Windows XP - it is "slow as hell" - but it works.
Yes I hear what you mean by "popping" sound. I can reproduce it.
I will look into it in the near future...

**Comment by malbanGit** [comment]
Soso...
After 1 1/2 days of bug tracking and sound research... I implemented completely new sound routines.
It seems that:
a) Java under windows and mac differ in sound stuff
b) java does not like 8bit sounds, 

Now I implemented a 16 bit sound with mixer and some other stuff (heavily refused some code from:
https://github.com/finnkuusisto/TinySound

But - the good news is - it works and at least I don't hear that crackling sound anymore. Next update I will do... you can unplug the earplugs :-)

**Comment by mountaingoate** [comment]
Sounds great! (no pun intended :-)
