### ISSUE TITLE
error java on boot

### ISSUE THREAD

**Issue by benjaboyy** [malbanGit/Vide#9]
I run the recent version of JAVA on my pc.
A friend develops stuff also on the newest version of java and no problems.
But when boot Vide i need to update to JAVA 10,

![image](https://user-images.githubusercontent.com/16157766/50560152-2a27f900-0cfe-11e9-9331-f8c3c5fd2789.png)

**Comment by malbanGit** [comment]
Well - like the screenshot says - are you sure you have Java 10 installed?
What does the log file say? (Vide/log/.... most recent file in there)

It should report what Java version was found - please post the first 10 lines or so...

If all else fails - you can start Vide with command line Parameter "-vt-" than the java version test is omitted.

If you truely have a version 10 and the above dialog appears - it IS a bug - but I nonetheless would like to see the log entries - because the version test is build on the system propertiers...
"
                String javaVersion = System.getProperty("java.version");
"
There can't be much going on wrong there ...

**Comment by benjaboyy** [comment]
The problem was on me... 
The current released version was 8. but there was a development version higher than 10.
So my bad for not checking and taking up your time.
